apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: sangeeta02/backend-app-workflow:v1
        ports:
        - containerPort: 5000
        env:
          - name: DB-PORT
            valueFrom: 
              configMapKeyRef:
                name: db-details
                key: PORT
          - name: DB-URI
            valueFrom:
              configMapKeyRef:
                name: db-details
                key: MONGO_URI
           